### ISSUE TITLE
Remove dist folder from version control

### ISSUE THREAD

**Issue by avdeev** [karambafe/match-media-breakpoint#3]
Small discussion here
https://github.com/rollup/rollup-starter-lib/issues/8

**Comment by karambafe** [comment]
@avdeev what about installing package from github? Without this folder, the library will not work

**Comment by avdeev** [comment]
@karambafe Yep, i asked about it in the linked discussion :)

Github (GIT) is the source store.
To distribute the code it's recommended to use NPM registry, CDNs (https://unpkg.com/match-media-breakpoint), etc.

**Comment by karambafe** [comment]
ok, I deleted the folder `dist` in version [1.1.0](https://github.com/karambafe/match-media-breakpoint/releases/tag/v1.1.0)
